var rule={
    title:'66西瓜',
    host:'https://www.ledlmw.com',
    url:'/fyclass-fypage.html',
    searchUrl:'/baidu**/page/fypage.html',
    searchable:1,quickSearch:1,play_parse:true,limit:6,
    headers:{'User-Agent':'MOBILE_UA'},
    class_parse:'.myui-header__menu&&.dropdown-box&&li:gt(0):lt(6);a&&Text;a&&href;.*/(.*?).html',
    cate_exclude: '明星',tab_exclude: '类型|年份|TAG',
    lazy:'',
    推荐:'*',
    一级:'.myui-vodlist li;a&&title;a&&data-original;.pic-text&&Text;a&&href',
    二级:{title:'h1&&Text',
    img:'.lazyload&&src',
    desc:'.text-muted:eq(-1)&&Text;.text-muted:eq(-5)&&Text;.myui-content__detail p:eq(4)&&Text;.myui-content__detail p:eq(5)&&Text;.myui-content__detail p:eq(6)&&Text',
    content:'.content&&Text',
    tabs:'.nav.nav-tabs a',
    lists:'.myui-content__list:eq(#id) li'},
    搜索:'.myui-vodlist__media li;a&&title;*;*;a&&href;.detail&&p:eq(2)&&Text',
}