var rule = {
            title: 'CN影院',
            host: 'https://www.cnys2.tv/',
            url: '/vodshow-fyclass.html',
            searchUrl: '/vodsearch-page-fypage-wd-**.html',
            searchable: 1,
            quickSearch: 1,
            filterable: 0,
            filter: '',
            filter_url: '',
            filter_def: {},
            headers: {
                'User-Agent': 'MOBILE_UA',
            },
            timeout: 5000,
            class_parse: '.swiper-wrapper&&li;a&&Text;a&&href;/vodtype-(.*?).html',
            cate_exclude: '',
            play_parse: true,
            lazy: `js:input = {parse: 1, url: input, js: ''}`,
            double: true,
            推荐: 'body&&.public-list-box;.public-list-bj;a&&title;img&&data-src;.public-list-title&&Text;a&&href',
            一级: 'div.public-list-box a;img&&alt;img&&data-src;.public-list-title&&Text;a&&href',
            二级: {
                title: 'h3&&Text;',
                img: '.mask-0&&data-src',
                desc: ';.slide-info-remarks&&Text;;.slide-info.hide:eq(2)&&Text;.slide-info.hide:eq(1)&&Text',
                content: '.text.cor4&&Text',
                tabs: '.anthology-tab a',
                lists: '.anthology-list-play:eq(#id)&&li',
                tab_text: 'body&&Text',
                list_text: 'body&&Text',
                list_url: 'a&&href'
            },
            搜索: '.search-box;.thumb-txt&&Text;img&&data-src;.public-list-title&&Text;a&&href',
        }