var rule = {
    title: 'OmoFun[漫]',
    host:'http://www.omofuns.cc/',
   /* host:'http://fb.omofun.one',
    hostJs: $js.toString(() => {
        print(HOST);
        let html = request(HOST, {headers: {"User-Agent": PC_UA}});
        let src = jsp.pdfh(html, "dl&&a:eq(0)&&href");
        print(src);
        HOST = src;
    }),*/
    url:'/index.php/vod/show/fyfilter.html',
    searchUrl: '/index.php/vod/search/page/fypage/wd/**.html',
    searchable: 1,quickSearch: 0,filterable: 1,play_parse: true,double: true,timeout: 5000,
    filter: {"id/20":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""},{"n":"搞笑","v":"class/搞笑"},{"n":"运动","v":"class/运动"},{"n":"励志","v":"class/励志"},{"n":"武侠","v":"class/武侠"},{"n":"特摄","v":"class/特摄"},{"n":"热血","v":"class/热血"},{"n":"战斗","v":"class/战斗"},{"n":"竞技","v":"class/竞技"},{"n":"校园","v":"class/校园"},{"n":"青春","v":"class/青春"},{"n":"爱情","v":"class/爱情"},{"n":"冒险","v":"class/冒险"},{"n":"后宫","v":"class/后宫"},{"n":"百合","v":"class/百合"},{"n":"治愈","v":"class/治愈"},{"n":"萝莉","v":"class/萝莉"},{"n":"魔法","v":"class/魔法"},{"n":"悬疑","v":"class/悬疑"},{"n":"推理","v":"class/推理"},{"n":"奇幻","v":"class/奇幻"},{"n":"神魔","v":"class/神魔"},{"n":"恐怖","v":"class/恐怖"},{"n":"血腥","v":"class/血腥"},{"n":"机战","v":"class/机战"},{"n":"战争","v":"class/战争"},{"n":"犯罪","v":"class/犯罪"},{"n":"社会","v":"class/社会"},{"n":"职场","v":"class/职场"},{"n":"剧情","v":"class/剧情"},{"n":"伪娘","v":"class/伪娘"},{"n":"耽美","v":"class/耽美"},{"n":"歌舞","v":"class/歌舞"},{"n":"肉番","v":"class/肉番"},{"n":"美少女","v":"class/美少女"},{"n":"吸血鬼","v":"class/吸血鬼"},{"n":"泡面番","v":"class/泡面番"},{"n":"欢乐向","v":"class/欢乐向"}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""},{"n":"大陆","v":"area/大陆"},{"n":"韩国","v":"area/韩国"},{"n":"香港","v":"area/香港"},{"n":"台湾","v":"area/台湾"},{"n":"日本","v":"area/日本"},{"n":"美国","v":"area/美国"},{"n":"泰国","v":"area/泰国"},{"n":"英国","v":"area/英国"},{"n":"新加坡","v":"area/新加坡"},{"n":"其他","v":"area/其他"}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""},{"n":"2024","v":"year/2024"},{"n":"2023","v":"year/2023"},{"n":"2022","v":"year/2022"},{"n":"2021","v":"year/2021"},{"n":"2020","v":"year/2020"},{"n":"2019","v":"year/2019"},{"n":"2018","v":"year/2018"},{"n":"2017","v":"year/2017"},{"n":"2016","v":"year/2016"},{"n":"2015","v":"year/2015"},{"n":"2014","v":"year/2014"},{"n":"2013","v":"year/2013"},{"n":"2012","v":"year/2012"},{"n":"2011","v":"year/2011"},{"n":"2010","v":"year/2010"},{"n":"2009","v":"year/2009"},{"n":"2008","v":"year/2008"},{"n":"2007","v":"year/2007"},{"n":"2006","v":"year/2006"},{"n":"2005","v":"year/2005"},{"n":"2004","v":"year/2004"},{"n":"更早","v":"year/更早"}]},{"key":"by","name":"排序","value":[{"n":"按最新","v":"by/time"},{"n":"按最热","v":"by/hits"},{"n":"按评分","v":"by/score"}]}],
    "id/22":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""},{"n":"搞笑","v":"class/搞笑"},{"n":"运动","v":"class/运动"},{"n":"励志","v":"class/励志"},{"n":"武侠","v":"class/武侠"},{"n":"特摄","v":"class/特摄"},{"n":"热血","v":"class/热血"},{"n":"战斗","v":"class/战斗"},{"n":"竞技","v":"class/竞技"},{"n":"校园","v":"class/校园"},{"n":"青春","v":"class/青春"},{"n":"爱情","v":"class/爱情"},{"n":"冒险","v":"class/冒险"},{"n":"后宫","v":"class/后宫"},{"n":"百合","v":"class/百合"},{"n":"治愈","v":"class/治愈"},{"n":"萝莉","v":"class/萝莉"},{"n":"魔法","v":"class/魔法"},{"n":"悬疑","v":"class/悬疑"},{"n":"推理","v":"class/推理"},{"n":"奇幻","v":"class/奇幻"},{"n":"神魔","v":"class/神魔"},{"n":"恐怖","v":"class/恐怖"},{"n":"血腥","v":"class/血腥"},{"n":"机战","v":"class/机战"},{"n":"战争","v":"class/战争"},{"n":"犯罪","v":"class/犯罪"},{"n":"社会","v":"class/社会"},{"n":"职场","v":"class/职场"},{"n":"剧情","v":"class/剧情"},{"n":"伪娘","v":"class/伪娘"},{"n":"耽美","v":"class/耽美"},{"n":"歌舞","v":"class/歌舞"},{"n":"肉番","v":"class/肉番"},{"n":"美少女","v":"class/美少女"},{"n":"吸血鬼","v":"class/吸血鬼"},{"n":"泡面番","v":"class/泡面番"},{"n":"欢乐向","v":"class/欢乐向"}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""},{"n":"大陆","v":"area/大陆"},{"n":"韩国","v":"area/韩国"},{"n":"香港","v":"area/香港"},{"n":"台湾","v":"area/台湾"},{"n":"日本","v":"area/日本"},{"n":"美国","v":"area/美国"},{"n":"泰国","v":"area/泰国"},{"n":"英国","v":"area/英国"},{"n":"新加坡","v":"area/新加坡"},{"n":"其他","v":"area/其他"}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""},{"n":"2024","v":"year/2024"},{"n":"2023","v":"year/2023"},{"n":"2022","v":"year/2022"},{"n":"2021","v":"year/2021"},{"n":"2020","v":"year/2020"},{"n":"2019","v":"year/2019"},{"n":"2018","v":"year/2018"},{"n":"2017","v":"year/2017"},{"n":"2016","v":"year/2016"},{"n":"2015","v":"year/2015"},{"n":"2014","v":"year/2014"},{"n":"2013","v":"year/2013"},{"n":"2012","v":"year/2012"},{"n":"2011","v":"year/2011"},{"n":"2010","v":"year/2010"},{"n":"2009","v":"year/2009"},{"n":"2008","v":"year/2008"},{"n":"2007","v":"year/2007"},{"n":"2006","v":"year/2006"},{"n":"2005","v":"year/2005"},{"n":"2004","v":"year/2004"},{"n":"更早","v":"year/更早"}]},{"key":"by","name":"排序","value":[{"n":"按最新","v":"by/time"},{"n":"按最热","v":"by/hits"},{"n":"按评分","v":"by/score"}]}],
    "id/23":[{"key":"class","name":"剧情","value":[{"n":"全部","v":""},{"n":"搞笑","v":"class/搞笑"},{"n":"运动","v":"class/运动"},{"n":"励志","v":"class/励志"},{"n":"武侠","v":"class/武侠"},{"n":"特摄","v":"class/特摄"},{"n":"热血","v":"class/热血"},{"n":"战斗","v":"class/战斗"},{"n":"竞技","v":"class/竞技"},{"n":"校园","v":"class/校园"},{"n":"青春","v":"class/青春"},{"n":"爱情","v":"class/爱情"},{"n":"冒险","v":"class/冒险"},{"n":"后宫","v":"class/后宫"},{"n":"百合","v":"class/百合"},{"n":"治愈","v":"class/治愈"},{"n":"萝莉","v":"class/萝莉"},{"n":"魔法","v":"class/魔法"},{"n":"悬疑","v":"class/悬疑"},{"n":"推理","v":"class/推理"},{"n":"奇幻","v":"class/奇幻"},{"n":"神魔","v":"class/神魔"},{"n":"恐怖","v":"class/恐怖"},{"n":"血腥","v":"class/血腥"},{"n":"机战","v":"class/机战"},{"n":"战争","v":"class/战争"},{"n":"犯罪","v":"class/犯罪"},{"n":"社会","v":"class/社会"},{"n":"职场","v":"class/职场"},{"n":"剧情","v":"class/剧情"},{"n":"伪娘","v":"class/伪娘"},{"n":"耽美","v":"class/耽美"},{"n":"歌舞","v":"class/歌舞"},{"n":"肉番","v":"class/肉番"},{"n":"美少女","v":"class/美少女"},{"n":"吸血鬼","v":"class/吸血鬼"},{"n":"泡面番","v":"class/泡面番"},{"n":"欢乐向","v":"class/欢乐向"}]},{"key":"area","name":"地区","value":[{"n":"全部","v":""},{"n":"大陆","v":"area/大陆"},{"n":"韩国","v":"area/韩国"},{"n":"香港","v":"area/香港"},{"n":"台湾","v":"area/台湾"},{"n":"日本","v":"area/日本"},{"n":"美国","v":"area/美国"},{"n":"泰国","v":"area/泰国"},{"n":"英国","v":"area/英国"},{"n":"新加坡","v":"area/新加坡"},{"n":"其他","v":"area/其他"}]},{"key":"year","name":"年份","value":[{"n":"全部","v":""},{"n":"2024","v":"year/2024"},{"n":"2023","v":"year/2023"},{"n":"2022","v":"year/2022"},{"n":"2021","v":"year/2021"},{"n":"2020","v":"year/2020"},{"n":"2019","v":"year/2019"},{"n":"2018","v":"year/2018"},{"n":"2017","v":"year/2017"},{"n":"2016","v":"year/2016"},{"n":"2015","v":"year/2015"},{"n":"2014","v":"year/2014"},{"n":"2013","v":"year/2013"},{"n":"2012","v":"year/2012"},{"n":"2011","v":"year/2011"},{"n":"2010","v":"year/2010"},{"n":"2009","v":"year/2009"},{"n":"2008","v":"year/2008"},{"n":"2007","v":"year/2007"},{"n":"2006","v":"year/2006"},{"n":"2005","v":"year/2005"},{"n":"2004","v":"year/2004"},{"n":"更早","v":"year/更早"}]},{"key":"by","name":"排序","value":[{"n":"按最新","v":"by/time"},{"n":"按最热","v":"by/hits"},{"n":"按评分","v":"by/score"}]}]
    },
    filter_url: "{{fl.area}}/{{fl.by}}/{{fl.class}}/{{fl.cateId}}/page/fypage/{{fl.year}}",
    filter_def: {"id/20": {cateId: "id/20"},
        "id/22": {cateId: "id/22"},
        "id/23": {cateId: "id/23"}},
    headers: {
        "User-Agent": "MOBILE_UA"
    },
    class_name: '动漫电影&欧美动漫&日本动漫',
    class_url: 'id/22&id/23&id/20',
    lazy: `js:        var html = JSON.parse(request(input).match(/r player_.*?=(.*?)</)[1]);        var url = html.url;        if (html.encrypt == '1') {            url = unescape(url)        } else if (html.encrypt == '2') {            url = unescape(base64Decode(url))        }        if (/\\.m3u8|\\.mp4/.test(url)) {            input = {                jx: 0,                url: url,                parse: 0            }        } else {            input        }    `,
    推荐: '*',
    一级: '.hl-vod-list li;a&&title;.hl-lazy&&data-original;.public-list-prb&&Text;a&&href',
    二级: {
        "title": "h2&&Text",
        "img": ".hl-lazy&&data-original",
        "desc": ".module-info-item:eq(4)&&Text;.module-info-item:eq(2)&&Text;.module-info-item:eq(1)&&Text;li.col-xs-12--span:eq(0)&&Text;;",
        "content": ".hl-col-xs-12.blurb&&Text",
        "tabs": ".hl-plays-from.hl-tabs a",
        "lists": "#hl-plays-list:eq(#id)&&.hl-col-xs-4.hl-col-sm-2 a:not(.hl-show-list)"
    },
    搜索: '.hl-one-list.hl-theme-by li;*;*;.hl-pic-text&&Text;*;p:eq(0)&&Text',
}