var rule = {
    title: '八戒影视',
    host: 'http://www.bjtv.pw',
    url: '/vodtype/fyclass.html',
    searchUrl: '/vodsearch/**----------fypage---.html',
    searchable: 2,
    quickSearch: 0,
    class_parse: '.nav-menu-items&&li;a&&Text;a&&href;.*/(.*?).html',
    cate_exclude: '网址',
    play_parse: true,
    lazy: `js:        var html = JSON.parse(request(input).match(/r player_.*?=(.*?)</)[1]);        var url = html.url;        if (html.encrypt == '1') {            url = unescape(url)        } else if (html.encrypt == '2') {            url = unescape(base64Decode(url))        }        if (/\.m3u8|\.mp4/.test(url)) {            input = {                jx: 0,                url: url,                parse: 0            }        } else {            input        }    `,
    limit: 6,
    double: true,
    推荐: '.module-list;.module-items&&.module-item;a&&title;img&&data-src;.module-item-text&&Text;a&&href',
    一级: '.module-items .module-item;a&&title;img&&data-src;.module-item-text&&Text;a&&href',
    二级: {
        title: 'h1&&Text;.tag-link&&Text',
        img: '.module-item-pic&&img&&data-src',
        desc: '.video-info-items:eq(3)&&Text;.tag-link:eq(2)&&Text;.tag-link:eq(1)&&Text;.video-info-items:eq(1)&&Text;.video-info-items:eq(0)&&Text',
        content: '.vod_content&&Text',
        tabs: '.module-tab-item',
        lists: '.module-player-list:eq(#id)&&.scroll-content&&a',
        tab_text: 'div--small&&Text',
    },
    搜索: '.module-items .module-search-item;.video-serial&&title;img&&data-src;.video-serial&&Text;.video-serial&&href',
}