var rule = {
  title: '影视工厂',
  host: 'https://cdzhcz.com',
  class_name: '电影&电视剧&综艺&动漫',
  class_url: 'dianying_new&dianshiju_new&zongyi_new&dongman_new',
  searchUrl: '/vosearch/?wd=**',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/vos/fyclass/page/fypage/',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.swiper-wrapper li;a&&title;.lazyload&&data-original;.item-status&&Text;a&&href',
  一级: '.row li;a&&title;.lazyload&&data-original;.item-status&&Text;a&&href',
  二级: {
    title: 'h3&&Text',
    img: '.lazyload&&data-original',
    desc: '.row&&Text;.text-overflow:eq(1)&&Text;.text-overflow:eq(2)&&Text;.text-overflow&&Text;.text-overflow:eq(3)&&Text',
    content: '.text.text-row&&Text',
    tabs: '.playlist-tab&&li',
    tab_text: 'body&&Text',
    lists: '.ewave-playlist-content:eq(#id) li',
  },
  搜索: '*',
}