var rule = {
            title: '爱家影院',
            host: 'http://m.eajyy.com',
            url: '/List/fyclass--------fypage---.html',
            searchUrl: '/Search/**----------fypage---.html',
            searchable: 2,
            quickSearch: 0,
            filterable: 1,
            filter: '',
            filter_url: '',
            filter_def: {},
            headers: {
                'User-Agent': 'MOBILE_UA',
            },
            timeout: 5000,
            class_parse: '.top_nav&&li;a&&Text;a&&href;.*/(.*?).html',
            cate_exclude: '经典系列',
            play_parse: true,
            lazy: `js:input = {parse: 1, url: input, js: ''}`,
            double: true,
            推荐: 'ul.vodlist_wi&&li; li;*;*;*;*',
            一级: 'ul.vodlist&&li;a&&title;a&&data-original;.pic_text&&Text;a&&href',
            二级: {
                title: 'h2&&Text;.data&&a&&Text',
                img: '.lazyload&&data-original',
                desc: '.data_style&&Text;.data&&a:eq(2)&&Text;.data&&a:eq(1)&&Text;.data:eq(2)&&Text;.data:eq(3)&&Text',
                content: '.content_desc&&Text',
                tabs: '#NumTab&&a',
                lists: '.content_playlist:eq(#id)&&li',
                tab_text: 'a&&alt',
            },
            搜索: '*',
        }